Include Nextcloud update availability information
xperimental/nextcloud-exporter pull request #116
Opened 2024-04-13 12:52 UTC by monofox

This commit introduces new option and metric about nextcloud update availabilty information.

A new option was introduced called `--enable-info-update` which will append the to the Nextcloud serverinfo-URL a `&skipUpdate=false`.

In response, the update information is returned and provided in a new metric called `nextcloud_system_update_available`.

Example output if update available:
```
# HELP nextcloud_system_update_available Contains information whether a system update is available (0 = no, 1 = yes). In case of 1=yes, available_version label contains the new version.
# TYPE nextcloud_system_update_available gauge
nextcloud_system_update_available{available_version="28.0.4.1"} 1
```
Example output if update not available:
```
# HELP nextcloud_system_update_available Contains information whether a system update is available (0 = no, 1 = yes). In case of 1=yes, available_version label contains the new version.
# TYPE nextcloud_system_update_available gauge
nextcloud_system_update_available{available_version=""} 0
```

It was a bit tricky, as Nextcloud is reporting conflicting information (shortened excerpt):
```json
{
  "system": {
    "version": "28.0.4.1",
    "update": {
      "lastupdatedat": 0,
      "available": true,
      "available_version": "28.0.4.1"
    }
  }
}
```

Fixes xperimental/nextcloud-exporter#115

2024-04-18 18:39 UTC, xperimental commented
Hi @monofox . Thanks for the contribution :+1: 

I have seen the issue and this PR, but I had no time to look at this thoroughly yet. I had an idea to add this information when adding the `skipApps` code as well.

I'll probably not get to this until after the weekend, but I already enabled CI for this PR and it seems some tests need to be updated for the new code.

2024-04-18 19:31 UTC, monofox commented
Thank you  @xperimental . No hurry.
The failed tests results of situation, that the tests are currently running against a non-existing `nextcloud.example.com`. I wondered during extension of the tests, but expected to have a corresponding docker-container during test phase running to spawn this domain in an isolated test environment.

Just let me know, if (and which) changes should be done in this way.

2024-04-30 00:42 UTC, PReimers commented
@monofox I checked your tests.

The problem with the test is the expected URL does not match the actual URL.

Example 1:
expected: `https://nextcloud.example.com/ocs/v2.php/apps/serverinfo/api/v1/info?format=json&skipApps=false`
actual: `https://nextcloud.example.com/ocs/v2.php/apps/serverinfo/api/v1/info?format=json&skipApps=false&skipUpdate=false`

Example 2:
expected: `https://nextcloud.example.com/ocs/v2.php/apps/serverinfo/api/v1/info?format=json&skipUpdate=false&skipApps=false`
actual: `https://nextcloud.example.com/ocs/v2.php/apps/serverinfo/api/v1/info?format=json&skipApps=false&skipUpdate=false`

If I'm correct, the following code (`serverinfo/url.go`) would fix the tests:
(Changing the `wantURL` parameter)
```
                {
			desc:      "do not skip apps",
			serverURL: "https://nextcloud.example.com",
			wantURL:   "https://nextcloud.example.com/ocs/v2.php/apps/serverinfo/api/v1/info?format=json&skipApps=false&skipUpdate=false",
		},
		{
			desc:      "skip apps",
			serverURL: "https://nextcloud.example.com",
			skipApps:  true,
			wantURL:   "https://nextcloud.example.com/ocs/v2.php/apps/serverinfo/api/v1/info?format=json&skipApps=true&skipUpdate=false",
		},
		{
			desc:       "do not skip update",
			serverURL:  "https://nextcloud.example.com",
			skipUpdate: false,
			wantURL:    "https://nextcloud.example.com/ocs/v2.php/apps/serverinfo/api/v1/info?format=json&skipApps=false&skipUpdate=false",
		},
		{
			desc:       "skip update",
			serverURL:  "https://nextcloud.example.com",
			skipUpdate: true,
			wantURL:    "https://nextcloud.example.com/ocs/v2.php/apps/serverinfo/api/v1/info?format=json&skipApps=false&skipUpdate=true",
		},
		{
			desc:       "do not skip update and do not skip apps",
			serverURL:  "https://nextcloud.example.com",
			skipApps:   false,
			skipUpdate: false,
			wantURL:    "https://nextcloud.example.com/ocs/v2.php/apps/serverinfo/api/v1/info?format=json&skipApps=false&skipUpdate=false",
		},
```

2024-05-02 15:20 UTC, monofox commented
Thank you @PReimers for review and giving the right hint. I was blind for it. Fixed it. Test is fine on local machine.

2024-05-13 06:26 UTC, PReimers approved these changes

2024-05-31 22:17 UTC, xperimental requested changes
Finally managed to have a look at this (it's GPN :tada: ). Works fine, thanks for the contribution :slightly_smiling_face: 

I have added some small comments.

2024-07-16 20:02 UTC, xperimental commented
@monofox Do you have time to go through the review comments or do you want me to take over the PR?

2024-07-18 18:47 UTC, monofox commented on internal/metrics/collector.go
> +	// Fix small bug: its indicated as "true" even if there is no real update available.
Yes:
![image](https://github.com/user-attachments/assets/1cf0c631-d237-4bce-b637-cef1124be113)

You can see, that `system.update.available` is set to `true` and the `system.update.available_version` equals to `system.version`.

2024-07-18 19:00 UTC, monofox commented on internal/config/config.go
> +	flags.BoolVar(&result.Info.Update, "enable-info-update", defaults.Info.Update, "Enable gathering of system update-related metrics.")
I took it 1:1, thanks.

2024-07-18 19:04 UTC, monofox commented on serverinfo/serverinfo.go
> +// Update contains information about updates.
Taken 1:1, thanks.

2024-07-18 19:05 UTC, monofox commented on internal/metrics/collector.go
> +	metric, err := prometheus.NewConstMetric(systemUpdateAvailableDesc, prometheus.GaugeValue, updateAvailable, updateInfo...)
Thanks for this proposal. Due to my [previous comment](https://github.com/xperimental/nextcloud-exporter/pull/116#discussion_r1683327538) i at least kept the version check.

2024-07-18 19:06 UTC, monofox commented on internal/metrics/collector.go
> +		[]string{"available_version"}, nil)
Done 1:1. Earlier i thought, that this is not required, as the version number is already populated to `nextcloud_system_info`.

2024-07-18 19:11 UTC, monofox commented
> @monofox Do you have time to go through the review comments or do you want me to take over the PR?

Took a bit longer to get again free time. Thanks for your grateful comments. I've addressed them. Unfortunately, the check on the version number seems to be essential for proper indication whether an update is really available. See my comments above.

2024-07-18 20:57 UTC, xperimental commented on internal/metrics/collector.go
> +	// Fix small bug: its indicated as "true" even if there is no real update available.
Interesting. This did not happen for me so far. And currently I am at exactly the same version (`29.0.4.1`). Looks like there might be a bug in the serverinfo application then?

2024-07-21 18:44 UTC, monofox commented on internal/metrics/collector.go
> +	// Fix small bug: its indicated as "true" even if there is no real update available.
> edit: I noticed that "lastupdatedat" is also not zero for me. What does your environment look like (how do you install/run Nextcloud)?

I'm running Nextcloud installed without any docker container or similar. Just into plain stable debian + mariadb + php-fpm + redis + memcached.

The relevant code in `apps/serverinfo/lib/SystemStatistics.php` is:
```php
protected function getServerUpdateInfo(): array {
    $updateInfo = [
        'lastupdatedat' => (int) $this->config->getAppValue('core', 'lastupdatedat'),
        'available' => false,
    ];

    $lastUpdateResult = json_decode($this->config->getAppValue('core', 'lastupdateResult'), true);
    if (is_array($lastUpdateResult)) {
        $updateInfo['available'] = (count($lastUpdateResult) > 0);
        if (array_key_exists('version', $lastUpdateResult)) {
            $updateInfo['available_version'] = $lastUpdateResult['version'];
        }
    }

    return $updateInfo;
}
```

Interestingly, in the database, the value of `lastupdateResult` is `[]`, so available should be false. And `lastupdatedat` has a valid unix timestamp. In the JSON it is always given with `0`. 

Meanwhile the `available` got `false`. I guess, it is somehow an caching involved. At last time (when i've also made above screenshot), i just had freshly finished an update.

2024-08-02 17:28 UTC, xperimental commented on internal/metrics/collector.go
> +	// Fix small bug: its indicated as "true" even if there is no real update available.
Sorry for another delay. I finally also managed to trigger this behavior: it appears to happen after an update has been applied and before the next "update check" is done. The Webinterface shows this as "update check has not been completed, please try reloading the page".

I guess it's fine to leave this in then.

2024-08-02 17:31 UTC, xperimental approved these changes

2024-08-02 17:38 UTC, merged