`nextcloud_scrape_errors_total`: add ratelimit error cause
xperimental/nextcloud-exporter pull request #69
Opened 2022-03-27 15:27 UTC by noerw

2022-04-02 15:03 UTC, xperimental requested changes
Thanks for the contribution, this seems like a useful idea.

I have one small change idea.

2022-04-02 15:03 UTC, xperimental commented on internal/client/client.go
> +		if res.StatusCode == http.StatusTooManyRequests {
I think four cases is the point where I would replace the if-blocks with a switch.

2022-04-03 16:18 UTC, xperimental requested changes
I made a few other changes to the code yesterday. Can you rebase and add a test-case?

2022-04-22 11:37 UTC, nivadis commented
how does this come up? because i'm also facing this 429 errors, with 15s scrape, understandable. but I haven't found changes causing this now.

sorry for this little bit OT

2022-06-01 22:05 UTC, xperimental commented
@noerw It has been a while, but I have not checked in for some time as well...

Do you want to continue on this PR?

2022-06-05 08:47 UTC, noerw commented
I'm sure I rebased this change, but looks like I didn't push it. I'll push this once I'm home again in 2 weeks

2022-09-11 16:15 UTC, xperimental approved these changes

2022-09-11 16:16 UTC, merged